version: '3.8'

services:

  nasabah-db:
    image: postgres:15-alpine
    container_name: nasabah_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_nasabah
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nasabah-app:
    build: .
    container_name: nasabah_app_container
    ports:
      - "8080:9090"
    depends_on:
      - nasabah-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://nasabah-db:5432/db_nasabah
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data: