spring.application.name=nasabah


spring.datasource.name=db_nasabah
spring.datasource.url=jdbc:postgresql://localhost:5432/db_nasabah
spring.datasource.username=postgres
spring.datasource.password=user123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger - %msg%n

